### ISSUE TITLE
Homes being reset

### ISSUE THREAD

**Issue by AngelicBeatz** [ProjectEssentials/ProjectEssentials-Home#10]
### Describe the bug
> - A clear and concise description of what the bug is. 
every time the server is reset or restarted players homes are not being saved and in so they are lost and have to when they relog /sethome once again.
### Steps to reproduce the behavior
> - 1. Go to '...'
> - 2. Enter command '....'
> - 3. See error

new player logs in
player finds place for home
does /sethome home
plays for 7 hours with the /home working just fine
server restarts
player logs in to start the day and goes exploring
player does /home
error no home by the name of home found

### Expected behavior
> - A clear and concise description of what you expected to happen.

### Screenshots
> - If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/24941674/83445840-ba023300-a41b-11ea-8598-726acaa74ec7.png)

### Environment information
> - Project Essentials Home version: [e.g. v1.0.0.0]
> - Project Essentials Core version: [e.g. v0.3.0.0]
> - Project Essentials Modules version: [e.g. Permissions - v1.0.0.0; Essentials - v1.0.0.0]
> - Minecraft / Forge version: [e.g. 1.14.4 / 28.1.0]
![image](https://user-images.githubusercontent.com/24941674/83446808-5b3db900-a41d-11ea-91ab-fdf7788162b8.png)
Forge 1.15.2-forge-31.1.87

### Additional context
> - Add any other context about the problem here.
I am leaving my home now just message me either here or on discord I can let you on my server and you can see the issue or stream it to you, what you would like to do.

**Comment by MairwunNx** [comment]
@AngelicBeatz 👋, Thanks for issue! Yeah. I know about it problem, how you \ your hosting restarts server?

**Comment by MairwunNx** [comment]
https://github.com/ProjectEssentials/ProjectEssentials-Home/issues/5 check this issue

**Comment by AngelicBeatz** [comment]
I have to manually restart it because the pack still has issues, I am on Omnia 1.15.2

**Comment by MairwunNx** [comment]
Hmm, but forge not supports full server restart. 😃
Or you restarting server via `/stop` and launch script again?

**Comment by AngelicBeatz** [comment]
o really? your joking I didn't know that, I also am having Tick issues not TPS issues. My tps is 20 but my tick rate is at 40-60 XD

**Comment by AngelicBeatz** [comment]
no when I do stop it just does nothing, if I do restart it does nothing, if I do kill then I can start the server back up

**Comment by MairwunNx** [comment]
> o really? your joking I didn't know that, I also am having Tick issues not TPS issues. My tps is 20 but my tick rate is at 40-60 XD

How you math your tick rate?

**Comment by MairwunNx** [comment]
@AngelicBeatz 

> no when I do stop it just does nothing, if I do restart it does nothing, if I do kill then I can start the server back up

I think killing (btw, how you kill the server?) server is one of reasons why configurations not saved, you can see logs, before legal server shutting down all configurations saves, you can see it at logs.

This issue can't be reproduced by me, but if you still getting this issue - feedback here, this issue still open, if it problem not related force killing server . ¯\_(ツ)_/¯

**Comment by MairwunNx** [comment]
You still getting this issue? 
Also, you have this problem with other modules, warps, spawn?
