### ISSUE TITLE
We get an error using Home

### ISSUE THREAD

**Issue by DasFantatier** [ProjectEssentials/ProjectEssentials-Home#4]
### Describe the bug
> - I installed all 4 files (core, cooldown, permissions, home) for 1.15.2 like written on your homepage. The files are on our server and local.
I can connect to the server, and use /sethome, but when i use /home i get the error message "stackoverflow" on the client, the server log says "java.lang.IllegalAccessError: tried to access field net.minecraft.entity.Entity.field_70165_t from class com.mairwunnx.projectessentials.core.backlocation.BackLocationData"

### Steps to reproduce the behavior
> - always the same when trying, sometimes i get kicked from the server with the same client error message directly after connecting.

### Expected behavior
> - /home should teleport me to my /sethome location

### Screenshots
> - no screenshots

### Environment information
can´t find version numbers
> - Project Essentials Home version: latest download on your homepage for 1.15.2
> - Project Essentials Core version: latest download on your homepage for 1.15.2
> - Project Essentials Modules version:latest download on your homepage for 1.15.2
> - Minecraft / Forge version: [1.15.2 / 31.1.0]

### Additional context
> - Add any other context about the problem here.

### Log files. (latest.log and debug.log file in attachment)
[crash-2020-03-30_14.37.33-server.txt](https://github.com/ProjectEssentials/ProjectEssentials-Home/files/4402833/crash-2020-03-30_14.37.33-server.txt)
[crash-2020-03-30_14.40.02-server.txt](https://github.com/ProjectEssentials/ProjectEssentials-Home/files/4402834/crash-2020-03-30_14.40.02-server.txt)

**Comment by MairwunNx** [comment]
@DasFantatier 

You installed core module for 1.14.4 minecraft, `ProjectEssentials-Core-MOD-1.14.4-1.3.0.jar` - it string in your crash report. 

For 1.15.2 need core module with version 1.15.2.

**Comment by DasFantatier** [comment]
Thank you for this fast reply!WOW i can´t say how i could fail this much.... i could swear I clicked on the correct files.Very sorry for this dumb issue and thank you :)
 

-----Ursprüngliche Nachricht-----Von: "Pavel Erokhin" <notifications@github.com>Gesendet: Montag, 30. März 2020 15:54An: ProjectEssentials/ProjectEssentials-Home <projectessentials-home@noreply.github.com>Cc: DasFantatier <faith_of_sin@gmx.at>; Mention <mention@noreply.github.com>Betreff: Re: [ProjectEssentials/ProjectEssentials-Home] We get an error using Home (#4)</mention@noreply.github.com></faith_of_sin@gmx.at></projectessentials-home@noreply.github.com>


 
@DasFantatier
You installed core module for 1.14.4 minecraft, ProjectEssentials-Core-MOD-1.14.4-1.3.0.jar - it string in your crash report.
For 1.15.2 need core module with version 1.15.2.

**Comment by MairwunNx** [comment]
😁, No problem! Good luck 🍀 =).
