### ISSUE TITLE
"home can´t be found" message

### ISSUE THREAD

**Issue by DasFantatier** [ProjectEssentials/ProjectEssentials-Home#5]
### Describe the bug
> - Some people on our server have the issue that "/sethome" is working, but not "/home". Sometime it works the first 3 times, then the error appears " home with the name "home" can´t be found".
We use a server, i am server op and i don´t have this issue. So may it´s a problem with permissions?
Sadly i searched on your homepage and curseforge site and haven´t found a manual which i understand. 

Can you please help me if this is a permission problem and if yes what do i have to do that every player on the server can use it proper. I already found the descriptions on your homepage but guess I don´t understand it fully.

The 4 jar files are installed (core, perm., home, coold.) and I haven´t changed anything on the files, they are original.

I want that all players on the server can use /sethome and /home without any extra permissions for each player.

### Steps to reproduce the behavior
> - 1. Go to '...'
> - 2. Enter command '....'
> - 3. See error

### Expected behavior
> - All players can use /sethome and /home from beginning

### Screenshots
> - The message says "The home with the name "home" could not be found" 
![2020-03-31_16 20 37](https://user-images.githubusercontent.com/62701156/78039483-76813f00-736e-11ea-82fa-cf7d59814658.png)

### Environment information
> - Project Essentials Home version: [Project Essentials Home-1.15.2-1.1.0.jar]
> - Project Essentials Core version: [Project Essentials Core-MOD-1.15.2-1.1.0.jar]
> - Project Essentials Modules version: [Project Essentials Permissions-1.15.2-1.0.2.jar];
[Project Essentials Home-1.15.2-1.1.0.jar]
> - Minecraft / Forge version: [1.15.2 / 31.1.0]

### Additional context
> - Add any other context about the problem here.

### Log files. (latest.log and debug.log file in attachment)

Thank you in advice for your help!
Maybe there is a manual for dummies to give all player automatic permission for this command on the server, so I don´t have to change it always on.

**Comment by MairwunNx** [comment]
@DasFantatier welcome! It's not correct behavior, but currently i can't reproduce this problem.

You are sure what players set home before teleporting on home?
For example, if we type just `/sethome` without name argument, this automatically sets new home with name `home`.

i.e:

`/sethome` equals `/sethome home` and `/home` it equals `/home home`

For custom named home you need type `/sethome myhome` and teleport later `/home myhome`

If you get problems with homes, please, can you record on video this bug, and attach logs to issue.

**Comment by MairwunNx** [comment]
Also, can you get this problem when you not in overworld?

**Comment by DasFantatier** [comment]
@MairwunNx 

"You are sure what players set home before teleporting on home?"
-> Yes, they tried it multible times the last 2 days

"Also, can you get this problem when you not in overworld?"
-> Yes, the problem is in overworld and nether, it was just a coincidence that the screenshot was made in nether

We type "/sethome", the message appears that it was sucessfully set.
We type "/home" to teleport there, for me it´s working till now, for two of our players not. Sometimes "/home" works, 2 or 3 times, suddenly the message appears that there isn´t a home.

I look now for the log files and gonna upload them here

**Comment by MairwunNx** [comment]
@DasFantatier 
Strange bug.
~~Overworld too has this problem?~~ Can i join on your server and try reproduce this problem?

this bug 100% not related with permissions. All default player permissions already included.

**Comment by DasFantatier** [comment]
So, i got the logs now, number 5 have one "error message", number 7 more. They are from one player.
Our server hoster just had a homepage problem, so i gonna look for the server log now and post it.

Btw., the player tested /sethome and /home now again like 5 times and the issue didn´t happen now. Maybe we are lucky..... maybe not :D

searching for server files now

[2020-03-31-5.log](https://github.com/ProjectEssentials/ProjectEssentials-Home/files/4410490/2020-03-31-5.log)
[2020-03-31-7.log](https://github.com/ProjectEssentials/ProjectEssentials-Home/files/4410491/2020-03-31-7.log)

**Comment by DasFantatier** [comment]
Latest Server log and debug log.

[debug-1.log.gz](https://github.com/ProjectEssentials/ProjectEssentials-Home/files/4410569/debug-1.log.gz)
Here are a few of these messages from 2 players in the debug log:
[31Mar2020 11:22:21.415]
[31Mar2020 14:20:06.382]
[31Mar2020 14:20:36.337]
[31Mar2020 13:21:17.715]
[31Mar2020 13:21:29.853]


[Server_Log_2020-03-31-1.log.gz](https://github.com/ProjectEssentials/ProjectEssentials-Home/files/4410570/Server_Log_2020-03-31-1.log.gz)

**Comment by DasFantatier** [comment]
********
May i ask another question here which is not related to this topic:
As i searched the log files i found the command "/back" loaded from core. When i try it as OP it works, but not for the normal users. There is no "/back" command in the Project Essentials Core Command List. What to do to make it work for all?
********

**Comment by MairwunNx** [comment]
@DasFantatier i will try reproduce this problem on my test server. I give you feedback for any news.

**Comment by MairwunNx** [comment]
@DasFantatier yes, command back implemented in `core` module. `back` command permission by default not providing for players. You can add permission for players through permissions file or via command, `/perm group default set teleport.back`.

### P.S: Currently in last core module version `back` command has bug! After death you can't teleport back on your death coordinates. *It already fixed in core `2.0.0-RC.1+MC-1.14.4`, but will released later (It preview version, currently not able for download)*

**Comment by DasFantatier** [comment]
Thank you!

**Comment by MairwunNx** [comment]
Also @DasFantatier try update forge to latest version (`31.1.30`) when you using `31.1.0`. Maybe it forge bug. I don't know.

**Comment by DasFantatier** [comment]
Hello @MairwunNx 

About the /back command.
Yesterday I used the command /perm group default set teleport.back sucessfully and it worked for all players. We restarted the server in the night and now the /back doesn´t work again for all not OP players.
Have i done anything wrong?

I tried to edit the permission file but it seems i am too dumb to understand what to do, also with the manual on the homepage... Please help

**Comment by MairwunNx** [comment]
@DasFantatier how you reload server, what's it's mean? Forge not support server reloading (forge can reload only some server configurations no more).

All configurations automatically do save when you execute command `/stop`. (Not by forge shutting down server, e.g killing process or something like killing process)

Also please, open new issue related to `/back` command if you have problems with it, attach logs, attach `permissions.json` file.

**Comment by DasFantatier** [comment]
I use the restart button on nitrado

**Comment by MairwunNx** [comment]
@DasFantatier, I don't know how button on nitrado works.

If it button works incorrectly you can also after any manipulations with permissions just save with command `/perm save`. Try it. 🍀👍

**Comment by DasFantatier** [comment]
Worked, thank you!

**Comment by MairwunNx** [comment]
😉👍 Cool, @DasFantatier, if you will have any problem, create issue.

**Comment by MairwunNx** [comment]
Still getting a problem with homes? @DasFantatier, please feedback this if you still getting this issue.

**Comment by DasFantatier** [comment]
@MairwunNx soooooo, we tested the function the last 2 days now, the player which had the most problems first does not have any issues any more.
One other player had the issue one or two times yesterday. The next few times it worked again fine.

We are not able to test it with other forge because of all our mods.

I would guess this is an issue which can´t be propper traced back to any behavior or problem.
I would say let´s close this issue for now, if there are proper errors which can be handeled in the future I´m going to open a new one.

Thank you very much for this great mods and for your help here!

**Comment by MairwunNx** [comment]
@DasFantatier thanks! 🥰
My motivation to develop this mod is awesome old-atmosphere forge servers :).
