### ISSUE TITLE
Mod does not differentiate between worlds

### ISSUE THREAD

**Issue by audioblaster** [ProjectEssentials/ProjectEssentials-Home#8]
### Describe the bug
> The mod does not account for what world you are in when setting the home, making setting homes in all other dimensions than overworld useless.

### Steps to reproduce the behavior
> - 1. Set home in other world, in my case the nether
> - 2. Set a home
> - 3. Try to go to your home,
> - 4. Die to suffocation as the mod takes you to the overworld cordinates instead of the nether (or the world you sat the home in)

### Expected behavior
> - To get teleported to the same cordinates and world the home was set in

### Environment information
> - forge-28.2.3
> - Rest of the mods is attatched as a screenshot

### Additional context
> - Add any other context about the problem here.

### Log files. (latest.log and debug.log file in attachment)
^^ unaplicable, as there is no direct error
![mods](https://user-images.githubusercontent.com/63523203/79056999-88ab8900-7c5c-11ea-8352-b46364d83589.png)
^^

**Comment by MairwunNx** [comment]
@audioblaster, thanks for issue 👍, this bug will fixed in next version.

**Comment by MairwunNx** [comment]
Resolved, changes will included in 2.0.0 snapshot.
